name: CI/CD Pipeline
run-name: "${{ github.actor }} - ${{ github.run_id }}"

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
  pull_request:
    branches: [main]
    paths:
      - 'src/**'
  workflow_dispatch:
    inputs:
      buildMode:
        description: "Qual ação deseja fazer?"
        required: true
        default: 'Build'
        type: choice
        options:
          - Build
          - Build + Tag Validation
          - Build + Tag Validation + Deploy
      environments:
        description: "Selecione o ambiente de implantação"
        required: true
        type: environment


jobs:
  build:
    uses: felipementel/reusable-workflows/.github/workflows/python-sandbox-api-build.yml@main
    with:
      buildMode: 'Build + Push'
      environment: 'development'
      projectName: 'minha-api'
      imageName: 'minha-api'
      openapiFolder: 'open-api'
      registryUsername: 'felipementel'   # org no GHCR
    secrets:
      GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
      REGISTRY_PAT: ${{ secrets.REGISTRY_PAT }}

  deploy:
    needs: [build]
    if: needs.build.outputs.image-exists == 'false'
    uses: felipementel/reusable-workflows/.github/workflows/python-sandbox-api-deploy-aca.yml@main
    with:
      environment: 'development'
      tagVersion: ${{ needs.build.outputs.tag-version }}
      imageName: 'minha-api'
      registryUsername: 'felipementel'
      azureRgBase: ${{ vars.AZURE_RG }}
      acaeBaseName: ${{ vars.AZURE_ACAE_BASE }}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
